### ISSUE TITLE
for xCode 7.3, you need to enable option 'Weak References in Manual Retain Release'

### ISSUE THREAD

**Issue by yupferris** [zean00/fuse-qreader#1]
I don't think this is the case anymore. Have you tested it with Fuse 0.12.3?

Great work btw!

**Comment by zean00** [comment]
I'm using 0.12.3, turn out the problem with this weak references is in my code, after replacing the weak property and weak self, the error wouldn't occur anymore. But since I'm very new to iOS / Objective - C programming, I'm not sure what the side effect would be, but the code still work anyway

**Comment by yupferris** [comment]
aha, ok. I just remember Fuse having trouble with this a couple releases ago, but if it's specific to your code, I'm not gonna worry about it :)

Thanks for following up!
