### ISSUE TITLE
Fails on build

### ISSUE THREAD

**Issue by ElephantFishCrab** [zean00/fuse-qreader#3]
Hello! I've tried to download and preview your QR reader but it fails on build and the fuse command for installing displayed on README.md also results in errors. [My post on Fuse's community regarding this issue](https://www.fusetools.com/community/forums/howto_discussions/zean00s_qr_code_reader_-_fails_on_build).

Please help!

**Comment by oxovi** [comment]
Hi, I have the same issue on Android. iOS works great.
Anybody that has experience with the following problem?

"No resource found that matches the given name (at 'theme' with value '@style/Theme.AppCompat')"

Thanks in advance

**Comment by zean00** [comment]
Hi,

I don't have any issue compiling wth the latest fuse version (0.34), perhaps it's related to your Android SDK configuration, please make sure that you have Android Repository and Google Play Service in your SDK installation
